### ISSUE TITLE
希望下个版本增加调整字体大小的选项

### ISSUE THREAD

**Issue by bbszy** [thundernet8/Tinection#2]
希望前端文章内容页面有调整字体大小的选择。
后台最好也能能增加 标题 内容等调整字体大小的选项。

**Comment by quchenchen** [comment]
支持，目前字体设置找来找去非常复杂。希望改善。

**Comment by thundernet8** [comment]
目前正在花时间重写主题，请移步[Tint](https://github.com/thundernet8/Tinection-Pro)
