### ISSUE TITLE
新安装时有几个报错

### ISSUE THREAD

**Issue by brunoxu** [thundernet8/Tinection#4]
点击启用之后，有几个报错：

![image](https://cloud.githubusercontent.com/assets/1411063/11862162/9f92895a-a4c2-11e5-8392-2e152ce7689e.png)

·
Warning: mysql_query(): Access denied for user ''@'localhost' (using password: NO) in D:\develop\projects\myworks\brunoxu_www\codes\brunoxu\wp-content\themes\Tinection\admin\option\includes\ot-functions-admin.php on line 740

Warning: mysql_query(): A link to the server could not be established in D:\develop\projects\myworks\brunoxu_www\codes\brunoxu\wp-content\themes\Tinection\admin\option\includes\ot-functions-admin.php on line 740

Warning: mysql_num_rows() expects parameter 1 to be resource, boolean given in D:\develop\projects\myworks\brunoxu_www\codes\brunoxu\wp-content\themes\Tinection\admin\option\includes\ot-functions-admin.php on line 740
·

**Comment by thundernet8** [comment]
主题使用的后台设置框架比较老了，新的php版本已经移除了mysql而全面改用mysqli组件，所以将mysql_query改为mysqli_query，mysql_num_rows改为mysqli_num_rows
